#!/bin/bash
# TODO: when building with liblua.a instead of .so we end up duplicating the
# code which can have some performance implications.

MEMC_PATH=$1
SPARKEY_PATH=$2
# lua needs to be built with -fPIC for this to work.
# build with: cd vendor/lua ; make linux MYCFLAGS="-fPIC" or edit the Makefile
gcc -g -O2 -Wall -fPIC -c sparkey.c -I$MEMC_PATH/vendor/lua/src -I$SPARKEY_PATH/src/
gcc -fpic -shared -o sparkey.so sparkey.o -L$MEMC_PATH/vendor/lua/src -llua -L$SPARKEY_PATH/src/.libs/ -lsparkey -lsnappy -lzstd
echo -e "you probably want to:\ncp sparkey.so into $MEMC_PATH"
